### ISSUE TITLE
Node Overlap

### ISSUE THREAD

**Issue by anisurrahmansagor** [hophiphip/react-fishbone#1]
Nodes are overlapping to each other, it is difficult to view by dragging the node!
![overalapping after generating fishbone](https://github.com/hophiphip/react-fishbone/assets/42246281/50bf75be-8f78-415c-9358-2e04c989854b)

**Comment by arif98741** [comment]
Thanks @anisurrahmansagor for raising issue.

**Comment by hophiphip** [comment]
Initial fishbone implementation was based on d3 and d3-force. It was difficult to maintain and caused unnecessary node overlapping - that is why I completely changed fishbone chart implementation.

New version uses custom layout that was implemented without force layout and uses react-flow (xyflow) instead.

For now only the alterating edges layout is supported, which looks like this:
![alg-v2](https://github.com/user-attachments/assets/3f179c3d-8484-45dd-b152-7db5b19700c5)

New fishbone chart example is available here:  https://react-fishbone-docs.vercel.app/
